### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [3]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [4]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [5]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32


### Function 2 - your function to illustrate

In [11]:
"""
    torch.unsqueeze(input, dim) → Tensor
        Returns a new tensor with a dimension of size one inserted at the specified position.
"""


x = torch.randn(3, 4)
print(x.size())
y = torch.unsqueeze(input=x, dim=1)
print(y.size())

torch.Size([3, 4])
torch.Size([3, 1, 4])


In [19]:
"""
    torch.squeeze(input, dim=None, *, out=None) → Tensor
        Returns a tensor with all the dimensions of input of size 1 removed.
"""


x = torch.randn(3, 1, 5)
print(x.size())
y = torch.squeeze(input=x, dim=1)
print(y.size())

torch.Size([3, 1, 5])
torch.Size([3, 5])


### Function 3 - your function to illustrate

In [20]:
# Example 1 - ### your explanation ###
"""
    torch.transpose(input, dim0, dim1) → Tensor
        Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.
"""
### your code ###

x = torch.randn(2, 3)
print(x)
print(torch.transpose(input=x, dim0=0, dim1=1))

tensor([[-0.2255, -0.0549, -1.0023],
        [ 1.2030, -0.2151, -1.5281]])
tensor([[-0.2255,  1.2030],
        [-0.0549, -0.2151],
        [-1.0023, -1.5281]])


In [21]:
# Example 2 - ### your explanation ###
"""
    permute(*dims) → Tensor
        Returns a view of the original tensor with its dimensions permuted.
"""


### your code ###
x = torch.randn(3, 4, 5)
print(x.size())
print(x.permute(2, 1, 0).size())

torch.Size([3, 4, 5])
torch.Size([5, 4, 3])


### Function 4 - your function to illustrate

In [23]:
# Example 1 - ### your explanation ###
"""
    torch.reshape(input, shape) → Tensor
        Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying, but you should not depend on the copying vs. viewing behavior.
"""
### your code ###

x = torch.randn(3, 4, 5)
print(x.size())
x = torch.reshape(input=x, shape=(-1, 20))
print(x.size())

torch.Size([3, 4, 5])
torch.Size([3, 20])


In [25]:
# Example 2 - ### your explanation ###
"""
    view(*shape) → Tensor
        Returns a new tensor with the same data as the self tensor but of a different shape.
"""
### your code ###
x = torch.randn(3, 4, 5)
print(x.size())

print(x.view(size=(20, -1)).size())

torch.Size([3, 4, 5])
torch.Size([20, 3])


## others


In [8]:
# Example 1 - ### your explanation ###
"""
    torch.arange(start=0, end, step=1, *, out=None, 
                 dtype=None, layout=torch.strided, device=None, 
                 requires_grad=False) → Tensor
"""
### your code ###
a = torch.arange(start=0, end=10, step=2, dtype=torch.int8)
print(a)
print(a.shape)

tensor([0, 2, 4, 6, 8], dtype=torch.int8)
torch.Size([5])


In [10]:
# Example 2 - ### your explanation ###
"""
    torch.index_select(input, dim, index, *, out=None) → Tensor
        Returns a new tensor which indexes the input tensor along dimension dim using the entries in index which is a LongTensor.
"""
### your code ###

x = torch.randn(3, 4)
print(x)
indices = torch.tensor([0, 2])
y = torch.index_select(input=x, dim=0, index=indices)
print(y)

tensor([[-1.2384,  1.5458,  0.9011,  0.2040],
        [ 0.2400,  0.4589,  0.1948, -0.6302],
        [ 1.5336, -0.5663, -0.4765, -0.7545]])
tensor([[-1.2384,  1.5458,  0.9011,  0.2040],
        [ 1.5336, -0.5663, -0.4765, -0.7545]])
